default: &default
  adapter: mysql2
  encoding: utf8
  username: 'root'
  password: 'root'
  host: 'localhost'
  pool: 5

development:
  <<: *default
  database: MysteriousApp_development

test:
  <<: *default
  database: MysteriousApp_test

production:
  <<: *default
  database: MysteriousApp_production
  username: MysteriousApp
  password: <%= ENV['MYSTERIOUSAPP_DATABASE_PASSWORD'] %>
