User.create(username: 'admin', password: '123456', admin: true)
regular = User.create(username: 'regular', password: '123456')
someone = User.create(username: 'someone', password: '123456')
article = regular.articles.create(title: 'Article', content: 'Artcile content')
article.comments.create(content: 'comment from REGULAR', user: regular)
article.comments.create(content: 'comment from another user', user: someone)
